article/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = "article"

urlpatterns = [
    
    path('',views.articles,name = "articles"),
    
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('contact/',views.contact,name = "contact"),

    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view


from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('contact/',views.contact,name = "contact"),

    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),

    path('password-reset/',
            auth_view.PasswordResetView.as_view(
                    template_name='password_reset.html'), 
            name = "password_reset"),

    
    path('password-reset/done/',
            auth_view.PasswordResetDoneView.as_view(
                    template_name='password_reset_done.html'), 
            name = "password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/',
            auth_view.PasswordResetConfirmView.as_view(
                    template_name='password_reset_confirm.html'), 
            name = "password_reset_confirm"),

     path('password-reset-complete/',
            auth_view.PasswordResetCompleteView.as_view(
                    template_name='password_reset_complete.html'), 
            name = "password_reset_complete"),

 ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views

# from django.contrib.auth import views as auth_view

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('profile/',views.profile,name = "profile"),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author ")
    title = models.CharField(max_length =10000,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Created on")
    article_image = models.FileField(blank = True,null = True,verbose_name="Add article photo")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 1000,verbose_name = "Name")
    comment_content = models.CharField(max_length = 10000,verbose_name = "comments")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email=models.EmailField(max_length=254)
    phone = models.CharField(max_length=15)

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'rows':10, 'cols':35})
    )

article/views.py
from django.shortcuts import (render,HttpResponse,redirect,get_object_or_404,reverse)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from django.core.mail import EmailMessage
from django.template.loader import get_template

from .forms import ArticleForm,ContactForm
from .models import Article,Comment


# Create your views here.

tem_dir ="articles/"

def articles(request):
    query = request.GET.get("keyword")
    articles = Article.objects.all()
    
    if query:
        articles = Article.objects.filter(
            Q(title__icontains = query)|
             Q(content__icontains = query)
             ).distinct()
        # render(request,tem_dir+"articles.html",context)

    paginator = Paginator(articles,10)
    
    # page_request_var="page"
    page = request.GET.get('page',1) 
    
    # ?page = 2 
    articles = paginator.get_page(page)
    
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)



    context ={
            "articles":articles,
            "object_list":queryset,
            # "page_request_var":page_request_var,

                }

    return render(request,tem_dir+"articles.html",context)



def index(request):
    return render(request,tem_dir+"index.html")
    
def about(request):
    return render(request,tem_dir+"about.html")


@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article Created successfully")
        return redirect("article:dashboard")
    return render(request,tem_dir+"addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()   
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,tem_dir+"detail.html",{"article":article,"comments":comments})



@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article updated successfully")
        return redirect("article:dashboard")


    return render(request,tem_dir+"update.html",{"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Article deleted successfully")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    

def contact(request):
    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template =get_template(tem_dir+'contact_template.txt')
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            }
            content = template.render(context)

            email = EmailMessage(
                "New contact form submit from HarfhoBlog ",
                content,
                "Harfho Blog" +'',
                ['harfho77@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('contact')

    return render(request, tem_dir+'contact.html', {'form': form_class,})

article/templates/articles/about.html
{% extends "layout.html" %}


{% block body %}

<!-- {% load staticfiles%} -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About Me Profile card || Learning Robo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  </head>
  <body>

    <div class = "about-wrapper">
      <div class = "about-left">
        <div class = "about-left-content">
          <div>
            <div class = "shadow">
              <div class = "about-img">
                <img src = "{% static 'img/harfho1.jpg' %}" alt = "about image">
              </div>
            </div>

 <div class = "about-right">
      <div class = "about-btns">
                <h2><a href="https://github.com/Harfho" target="_blank"> <button type = "button" class = "btn btn-white">HARFHO</button></a></h2>
          </div><br>
        <h1>Hello<span>!</span></h1>

        <div class = "about-para">
          <p>I'm a Computer scientist, Lover of any things techs / Digital. @Harfho is versatile, creative,love learning, and enjoy working with others.</p>
        </div>
      </div>

          <ul class = "icons">
            <li><i class = "fab fa-facebook-f"></i><a href="https://www.facebook.com/harfho" target="_blank"> <button type = "button" class = "btn btn-success">Facebook</button></a></li><br>
            <li><i class = "fab fa-twitter"></i><a href="https://www.twitter.com/harfho" target="_blank"> <button type = "button" class = "btn btn-success">Twitter</button</a></li><br>
            <li><i class = "fab fa-linkedin"></i><a href="https://www.linkedin.com/in/harfho" target="_blank"> <button type = "button" class = "btn btn-success">Linkedin</button></a></li><br>
            <li><i class = "fab fa-instagram"></i><a href="https://www.instagram.com/harfho" target="_blank"> <button type = "button" class = "btn btn-success">Instagram</button></a></li><br>
          </ul>
        </div>

      </div>
    </div>
  </body>
</html>

{% endblock body %}

article/templates/articles/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Add article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add article</button>
        </form>
    </div>
  </div>


{% endblock body %}

article/templates/articles/articles.html
{% extends "layout.html" %}
<!-- {% load staticfiles%} -->
{% block body %}

<div class ="row">

        <div class="col-md|lg|sm-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Articles</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form method="GET" action="">{% csrf_token %}
                <input type="text" name = "keyword" class="input-sm" maxlength="100" placeholder="Find articles...">
              <button type="submit" class="btn btn-primary">Find</button>
            </form>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<br/>
    <div class="col-md|lg|sm-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      
        <br/><hr/>
      <!-- Author -->
      <p class="lead ">
      <img class="rounded-circle "  src="{% if user.is_authenticated %}
                                            {{ article.author.profile.image.url }}
                                          
                                          {% elif not  user.is_authenticated %}
                                                {{ article.author.profile.image.url }}
                                        
                                            {% else %}
                                                    {% static 'img/avatar_default.png' %}

                                          {% endif %}
                                        "

                                    width="50" height="50"/> Posted by {{article.author.username}} -
    
      <!-- Date/Time -->
    {{article.created_date|date:"F d Y"}}
  </p>
  <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="{{article.title}}" width="200" height="200" style="float: right"></a>
      {% endif %}


       <hr>

      <!-- Post Content -->
      <p class="lead" align="left">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-primary">Read more..</a>

      </div>
      </div>


{% endfor %}


{% else %}

<div class ="row">

    <div class="col-md|lg|sm-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   Article not found


<div align="right"> <a href="{% url 'article:dashboard'  %}" class="btn btn-info">Add Articles</a>
</div>
</div>
</div>
</div>
</div>

{% endif %}
<!-- <div class="pagination">
  <span class="step-links">
    {% if object_list.has_previous %}
      <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">previous</a>
    {% endif %}
    <span class="current">
      Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
    </span>

    {% if object_list.has_next %}
      <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">next</a>
    {% endif %}
  </span>
</div>
 -->

<br /><br />
    <ul class="pagination">
      {% if object_list.has_previous %}
        <li><a  class="btn btn-outline-info" href="?page={{ object_list.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">&laquo;</a></li>
      {% else %}
        <li class="disabled btn btn-outline-info"><span>&laquo;</span></li>
      {% endif %}

      {% for i in object_list.paginator.page_range %}
        {% if object_list.number == i %}
          <li class="active btn btn-outline-info "><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a class="btn btn-outline-info" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if object_list.has_next %}
        <li><a class="btn btn-outline-info" href="?page={{ object_list.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Next</a></li>
      {% else %}
        <li class="disabled btn btn-outline-info"><span>Next</span></li>
      {% endif %}
  </ul>
</div>

<!-- show this if user is not login -->

      {%  if not request.user.is_authenticated %}
      <hr>
        <marquee bgcolor='oldlace'><p class="lead" align="left" ><a href="{% url 'user:login' %}" class="btn btn-link">Sign-in</a> or
          <a href="{% url 'user:register' %}" class="btn btn-link">Register</a> to Add/post Articles</p></marquee>

      {% endif %}
{% endblock body %}

article/templates/articles/articles_bak.html
{% extends "layout.html" %}
<!-- {% load staticfiles%} -->
{% block body %}

<div class ="row">

        <div class="col-md offset-md-3">
            <div class="col-lg-8">
                <h3>Articles</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md offset-md-3">
        <div class="col-lg-8">
            <form method="GET" action="">{% csrf_token %}
                <input type="text" name = "keyword" class="input-sm" maxlength="100" placeholder="Find articles...">
              <button type="submit" class="btn btn-primary">Find</button>
            </form>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
    <div class="col-md offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      

      <!-- Author -->
      <p class="lead ">
      <img class="rounded-circle "  src="{% if user.is_authenticated %}
                                            {{ user.profile.image.url }}
                                          {% else %}
                                            {% static 'img/avatar_default.png' %}

                                          {% endif %}
                                        "

                                    width="50" height="50"/> Posted by {{article.author.username}} -
    
      <!-- Date/Time -->
    {{article.created_date|date:"F d Y"}}
  </p>
  <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="{{article.title}}"></a>
      {% endif %}


       <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-primary">Read more..</a>

      </div>
      </div>


{% endfor %}


{% else %}

<div class ="row">

    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   Article not found


<div align="right"> <a href="{% url 'article:dashboard'  %}" class="btn btn-info">Add Articles</a>
</div>
</div>
</div>
</div>
</div>

{% endif %}
<!-- <div class="pagination">
  <span class="step-links">
    {% if object_list.has_previous %}
      <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">previous</a>
    {% endif %}
    <span class="current">
      Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
    </span>

    {% if object_list.has_next %}
      <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">next</a>
    {% endif %}
  </span>
</div>
 -->

<div style ="float : center;">
    <ul class="pagination">
      {% if object_list.has_previous %}
        <li><a  class="btn btn-outline-info" href="?page={{ object_list.previous_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">&laquo;</a></li>
      {% else %}
        <li class="disabled btn btn-outline-info"><span>&laquo;</span></li>
      {% endif %}

      {% for i in object_list.paginator.page_range %}
        {% if object_list.number == i %}
          <li class="active btn btn-outline-info "><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a class="btn btn-outline-info" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if object_list.has_next %}
        <li><a class="btn btn-outline-info" href="?page={{ object_list.next_page_number }}{% if request.GET.keyword %}&keyword={{ request.GET.keyword }}{% endif %}">Next</a></li>
      {% else %}
        <li class="disabled btn btn-outline-info"><span>Next</span></li>
      {% endif %}
  </ul>
</div>

<!-- show this if user is not login -->

      {%  if not request.user.is_authenticated %}
      <hr>
        <marquee bgcolor='oldlace'><p class="lead" align="left" ><a href="{% url 'user:login' %}" class="btn btn-link">Sign-in</a> or
          <a href="{% url 'user:register' %}" class="btn btn-link">Register</a> to Add/post Articles</p></marquee>

      {% endif %}
{% endblock body %}

article/templates/articles/contact.html
<!DOCTYPE html>
{% extends "layout.html" %}

{% block body %}

<head>
<title>Contact</title>
</head>

<!------ Include the above in your HEAD tag ---------->
                <div class="container">
                    <div class="row">
                      <div class="col-md-6 col-md-offset-3">
                        <div class="well well-sm">
                          <form class="form-horizontal" role="form" action="" method="post">
                          <fieldset>
                            <legend class="text-center"><h1>Contact</h1></legend>

                            <div class="form-group col-md-5 col-md-offset-5">
                    
                                {% csrf_token %}
                                {{ form.as_p }}

                            </div>
                                <!-- Form actions -->
                                <div class="form-group">
                                <div class="col-md-12 text-right">
                                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                                </div>
                            </div>
                        </fieldset>
                    </form></div></div></div></div>


                <script src="//netdna.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
                <script src="//code.jquery.com/jquery-3.4.0.min.js"></script>

                {% endblock body %}

article/templates/articles/detail.html
{% extends "layout.html" %}

{% block title %}{{article.title}}{% endblock %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        Posted by {{article.author.username}}
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="" width="250" height="250">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}

      <div align="center">
      <a style ="float : right;" href="{% url 'article:dashboard' %}" class ="btn btn-danger">Add more Article</a></div>
      
      </p>
    </div> </div>


      <div class="col-md offset-md">
      
      <br><br><hr>

      <h4>COMMENT</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
        Be the first to comment on this article
      </div>
      {% endif %}
      <br><hr color="green">
      <div class="card my-4 col-md offset-md">
          <h5 class="card-header">Add comment:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Name</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter Your name">
                </div>
              <div class="form-group">
                  <label for="formGroupExampleInput">Comment</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Summit</button>
            </form>
          </div></div></div></div>
      

{% endblock body %}

article/templates/articles/index.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<head>
    <style>
  body {
    font: 20px Montserrat, sans-serif;
    line-height: 1.8;
    color: #f5f6f7;
  }
  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-1 { 
    background-color: #1abc9c; /* Green */
    color: #ffffff;
  }
  .bg-2 { 
    background-color: #474e5d; /* Dark Blue */
    color: #ffffff;
  }
  .bg-3 { 
    background-color: #ffffff; /* White */
    color: #555555;
  }
  .bg-4 { 
    background-color: #2f2f2f; /* Black Gray */
    color: #fff;
  }
  .container-fluid {
    padding-top: 10px;
    padding-bottom:1px;
  }
  .navbar {
    padding-top: 15px;
    padding-bottom: 15px;
    border: 0;
    border-radius: 0;
    margin-bottom: 0;
    font-size: 12px;
    letter-spacing: 5px;
  }
  .navbar-nav  li a:hover {
    color: #1abc9c !important;
  }
  </style>
</head>

<!-- Navbar -->


<!-- First Container -->
<div class="container-fluid bg-3 text-center">
  <h3 class="margin bg-1">Who Am I?</h3>
  <img src=" {% static 'img/harfhohome.jpg' %} " class="img-responsive img-circle margin" style="display:inline" alt="harfho" width="350" height="350">
  <!-- <img src="bird.jpg"> -->
  <h3>I'm an adventurer<br></h3>
  <p>computer Scientist</p>
</div>

<!-- Second Container -->
<div class="container-fluid bg-2 text-center">
  <h3 class="margin bg-1">What Am I?</h3>
  <p>Am creative,<br>Easygoing,<br>Encouraging,<br>Caring,<br>Sharing,<br>Calm,<br>Varsertile<br>&<br> I love learning.
</div>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center">    
  <h3 class="margin bg-1">Where To Find Me?</h3><br>
  <div class="row">
    <div class="col-sm-4">
      
      <a href="https://www.facebook.com/harfho"> <img src=" {% static 'img/facebook.png' %} " class="img-responsive margin" style="width:50%" alt="Image"></a>
    </div>
    <div class="col-sm-4"> 
      
      <a href="https://www.linkedin.com/in/harfho"><img src=" {% static 'img/linkedin.png' %} " class="img-responsive margin" style="width:50%" alt="Image"></a>
    </div>
    <div class="col-sm-4"> 
      <a href="https://www.twitter.com/harfho"><img src=" {% static 'img/twitter.png' %} " class="img-responsive margin" style="width:50%" alt="Image"></a>
    </div></div>

<p >
        {% if request.user.is_authenticated %}
                <strong>{{request.user.username}}</strong> You haved logged-in
        {% else %}
            You are not log-in
            <p class="lead">
              <a href="{% url 'user:login' %}" class="btn btn-link">Sign-in</a>or<a href="{% url 'user:register' %}" class="btn btn-link">Register</a>to Add/post Articles</p>
        {% endif %}

</p>

</div>

{% endblock body %}

article/templates/articles/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update article</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update article</button>
        </form>
    </div>
  </div>


{% endblock body %}