article/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = "article"

urlpatterns = [
    
    path('',views.articles,name = "articles"),
    
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('contact/',views.contact,name = "contact"),

    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view


from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('contact/',views.contact,name = "contact"),

    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),

    path('password-reset/',
            auth_view.PasswordResetView.as_view(
                    template_name='password_reset.html'), 
            name = "password_reset"),

    
    path('password-reset/done/',
            auth_view.PasswordResetDoneView.as_view(
                    template_name='password_reset_done.html'), 
            name = "password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/',
            auth_view.PasswordResetConfirmView.as_view(
                    template_name='password_reset_confirm.html'), 
            name = "password_reset_confirm"),

     path('password-reset-complete/',
            auth_view.PasswordResetCompleteView.as_view(
                    template_name='password_reset_complete.html'), 
            name = "password_reset_complete"),

 ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from . import views

# from django.contrib.auth import views as auth_view

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('profile/',views.profile,name = "profile"),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author ")
    title = models.CharField(max_length =10000,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Created on")
    article_image = models.FileField(blank = True,null = True,verbose_name="Add article photo")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 1000,verbose_name = "Name")
    comment_content = models.CharField(max_length = 10000,verbose_name = "comments")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email=models.EmailField(max_length=254)
    phone = models.CharField(max_length=15)

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'rows':10, 'cols':35})
    )

article/views.py
from django.shortcuts import (render,HttpResponse,redirect,get_object_or_404,reverse)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from django.core.mail import EmailMessage
from django.template.loader import get_template

from .forms import ArticleForm,ContactForm
from .models import Article,Comment


# Create your views here.

tem_dir ="articles/"

def articles(request):
    query = request.GET.get("keyword")
    articles = Article.objects.all()
    
    if query:
        articles = Article.objects.filter(
            Q(title__icontains = query)|
             Q(content__icontains = query)
             ).distinct()
        # render(request,tem_dir+"articles.html",context)

    paginator = Paginator(articles,10)
    
    # page_request_var="page"
    page = request.GET.get('page',1) 
    
    # ?page = 2 
    articles = paginator.get_page(page)
    
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)



    context ={
            "articles":articles,
            "object_list":queryset,
            # "page_request_var":page_request_var,

                }

    return render(request,tem_dir+"articles.html",context)



def index(request):
    return render(request,tem_dir+"index.html")
    
def about(request):
    return render(request,tem_dir+"about.html")


@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article Created successfully")
        return redirect("article:dashboard")
    return render(request,tem_dir+"addarticle.html",{"form":form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()   
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,tem_dir+"detail.html",{"article":article,"comments":comments})



@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Article updated successfully")
        return redirect("article:dashboard")


    return render(request,tem_dir+"update.html",{"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Article deleted successfully")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    

def contact(request):
    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'contact_name'
            , '')
            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template =get_template(tem_dir+'contact_template.txt')
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            }
            content = template.render(context)

            email = EmailMessage(
                "New contact form submit from HarfhoBlog ",
                content,
                "Harfho Blog" +'',
                ['harfho77@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('contact')

    return render(request, tem_dir+'contact.html', {'form': form_class,})

article/templates/includes/footer.html
    
  
       <footer class="footer-basic-centered">



      
      <p class="footer-company-name">HARFHO BLOG</p>

      <p class="footer-links">

        <a href="/">Home</a>
        ---
        <a href="/articles">Blog</a>
        ---
        <!-- <a href="#">Pricing</a> -->
        <!-- --- -->
        <a href="/about">About</a>
        ---
        <!-- <a href="#">Faq</a> -->
        <!-- --- -->
        <a href="/contact">Contact</a>
      </p>

      <p class="footer-company-name">&copy; 2019</p>



    </footer>

article/templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <a class="navbar-brand" href="{% url 'index'  %}">Home</a>
         <a class="nav-link" href="{% url 'article:articles'  %}">Blog</a>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <!-- <li class="nav-item active">
              <a class="navbar" href="{% url 'article:articles'  %}">Articles</a>
            </li> -->
            
            <li class="nav-item active">
                <a class="nav-link " href="{% url 'about'  %}">About</a> 
            </li>
            
          </ul>
          <br/>
          <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
             

            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:profile'  %}">Profile</a>
            </li>
              
             
             <li class="nav-item active">
              <a class="nav-link" href="{% url 'article:dashboard'  %}">Control Panel</a>
            </li>
            
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:logout'  %}">Log out</a>
            </li>
          {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:login'  %}" >Sign in</a>
              </li>
              
              
              <li class="nav-item active  ">
                <a class="nav-link" href="{% url 'user:register'  %}">Register</a>
              </li>
          {% endif %}
        </ul>
        </div>
    
    
</nav>